@startuml 图片信息tag串联

' 实体
package "房源信息表" {
[Hive table1]
[Hive table2]
[Hive table3]
[Hive table4]
}
note left: 解读@郭琦

[汇总信息表] 
note left: @何家俊
[图片tag能力]
note left: @王玉梁 @牛强
[图片tag表]
note left: @牛强 @王玉梁
[汇总产出表]
note left: @何家俊

'关系
[Hive table1] --> [汇总信息表]
[Hive table2] --> [汇总信息表]
[Hive table3] --> [汇总信息表]
[Hive table4] --> [汇总信息表]

[汇总信息表] --> [图片tag能力] : 调度任务1
[图片tag能力] --> [图片tag表]

[汇总信息表] --> [汇总产出表] : 调度任务2
[图片tag表] --> [汇总产出表] : 调度任务2

@enduml